name: Delete cidr-calculator from Akamai Functions

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    name: Delete Static App
    steps:
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1

      - name: Install the aka Plugin for Spin
        run: spin plugins update && spin plugins install aka --yes

      - name: Login to Akamai Functions
        run: spin aka login --token ${{ secrets.AKAMAI_FUNCTIONS_TOKEN }}

      - name: Check if App exists
        id: check
        run: |
          if spin aka apps list --account-id ${{ secrets.AKAMAI_FUNCTIONS_ACCOUNT_ID }} | grep -xF "cidr-calculator" > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "App cidr-calculator found."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "App cidr-calculator not found, nothing to delete."
          fi

      - name: Delete cidr-calculator from Akamai Functions
        if: steps.check.outputs.exists == 'true'
        run: spin aka app delete --app-name cidr-calculator --account-id ${{ secrets.AKAMAI_FUNCTIONS_ACCOUNT_ID }} --no-confirm
